{
 "title": "Weather Station",
 "tags": [
  "starlink",
  "AIRMAR",
  "v1.0.0"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align-last: center\">\n  <!-- <img src=\"https://i.ibb.co/254s0jQ/3-stars.png\" width=\"55\" style=\"margin-bottom: 1rem\"> -->\n  <h1 style=\"text-align: center\">\n    <b>Starlink Weather Station</b>\n  </h1>\n</div>\n\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up{} or on() vector(0)" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AIRMAR_TWA" }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AIRMAR_TWA" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AIRMAR_TWS" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AIRMAR_TEMPERATURE" }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AIRMAR_BAROMETER" }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    { "expr": "AIRMAR_TWA" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    { "expr": "AIRMAR_TWS" }
   ]
  }
 ]
}